# Process Data from CSV to GeoJSON

```{r}
# Read in CSV file
df <- read.csv("data/csv/hourly_load_per_gps_location_night_charging_only.csv")


# pull out the Lat / Lon of each school into schools df
schools <- df[!duplicated(df$School_name), c("School_name", "Lat", "Lon")]

# assign a unique ID to each school
schools$ID <- seq.int(nrow(schools))

# drop the Lat / Lon from the main df
df <- df[, -c(1, 6, 7)]

# replace School_name with ID in df
df$School_name <- schools$ID[match(df$School_name, schools$School_name)]
# rename School_name to ID
colnames(df)[4] <- "school_id"
colnames(df)[3] <- "day"

# replace days of the week with integers 1-7
# create a map of the days of the week
days <- c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
# create a second map of the integers 1-7
days_int <- c(1, 2, 3, 4, 5, 6, 7)

# replace the days of the week with integers
df$day <- days_int[match(df$day, days)]

# create a new column that is hour of the week (1-168) using the Day and hour columns
df$timestep <- (df$day - 1) * 24 + df$hour

View(df)

# export to csv
write.csv(df, "data/csv/hourly_load_timesteps.csv", row.names = FALSE)
write.csv(schools, "data/csv/schools.csv", row.names = FALSE)
```

## Convert Schools DF to GeoJSON
```{r}
# read in schools csv
schools <- read.csv("data/csv/schools.csv")
library(sf)
# convert to shapefile with points for Lat / Lon
schools <- st_as_sf(schools, coords = c("Lon", "Lat"), crs = 4326)
View(schools)
# write to geojson
st_write(schools, "data/json/schools.geo.json", driver = "GeoJSON")
```
